version: "3"

services:


  wordpress:
    image: wordpress:5.4.2-php7.3-apache
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env


  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/configs/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env
    


  nginx:
    container_name: nginx
    image: linuxserver/letsencrypt
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/config:/config
      - ./docker/nginx/nginx.conf:/config/nginx/site-confs/default
      - ./docker/nginx/ssl.conf:/config/nginx/ssl.conf
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Merida
      - URL=arido.dev
      - SUBDOMAINS=www,iot,www.iot,
      - VALIDATION=http
      - STAGING=false #optional